{{- if and (not .Values.secrets.existingSecret) (or .Values.secrets.masterEncryptionKey .Values.secrets.dbDsn) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaults-syncer.fullname" . }}
  labels:
    {{- include "vaults-syncer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.masterEncryptionKey }}
  MASTER_ENCRYPTION_KEY: {{ .Values.secrets.masterEncryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.dbDsn }}
  DB_DSN: {{ .Values.secrets.dbDsn | b64enc | quote }}
  {{- end }}
{{- end }}
